version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - pwd
artifacts:
  base-directory: client, lib
  files:
    - '**/*'
#    artifact1:
#      files:
#        - 'lib/client/*'
#    artifact2:
#      files:
#        - 'lib/server/*'