version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - echo Build succeeded
    - aws s3 cp lib/client/* s3://nodejs-chess --recursive
artifacts:
  files:
    - README.md
    - package.json
    - config.js
    - gulpfile.js
    - node_modules/**/*
    - lib/**/*
    - client/**/*
    - tasks/*
    - rds-combined-ca-bundle.pem
    - npm-shrinkwrap.json
#    artifact1:
#      files:
#        - 'lib/client/*'
