version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - echo Build succeeded
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: lib/client/
      files:
        - '**/*'
    artifact2:
      files:
    - README.md
    - package.json
    - config.js
    - gulpfile.js
    - node_modules/**/*
    - lib/server/**/*
    - lib/common/**/*
    - client/**/*
    - tasks/*
    - rds-combined-ca-bundle.pem
    - npm-shrinkwrap.json