version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - pwd
artifacts:
  files:
    - README.md
    - package.json
    - config.js
    - gulpfile.js
    - node_modules/**/*
    - lib/**/*
    - clinet/**/*
    - rds-combined-ca-bundle.pem
    - npm-shrinkwrap.json
#    artifact1:
#      files:
#        - 'lib/client/*'
#    artifact2:
#      files:
#        - 'lib/server/*'