version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - aws s3 cp lib/client/ s3://node-for-test --recursive

artifacts:
  files:
    - README.md
    - package.json
    - config.js
    - gulpfile.js
    - node_modules/**/*
    - lib/**/*
    - client/**/*
    - tasks/*
    - test/**/*
    - rds-combined-ca-bundle.pem
    - npm-shrinkwrap.json

