version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.22.7
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - echo Build completed
artifacts:
  base-directory: lib/client
  files:
    - '**/*'
#    artifact1:
#        - 'lib/server/*'
